CREATE DATABASE SENAI_HROADS_TARDE;

USE SENAI_HROADS_TARDE;

CREATE TABLE CLASSES(

	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(250) NOT NULL UNIQUE 
);

CREATE TABLE TIPO_HABILIDADE(

	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(250) NOT NULL UNIQUE 
);

CREATE TABLE HABILIDADES(

	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(250) NOT NULL UNIQUE 
	,ID_TIPO_HABILIDADE INT FOREIGN KEY REFERENCES TIPO_HABILIDADE(ID) NOT NULL
);

CREATE TABLE CLASSES_HABILIDADES(

	ID_CLASSE INT FOREIGN KEY REFERENCES CLASSES(ID) NOT NULL
	,ID_HABILIDADE INT FOREIGN KEY REFERENCES HABILIDADES(ID) NOT NULL
);

CREATE TABLE PERSONAGEM(

	ID INT IDENTITY PRIMARY KEY 
	,NOME VARCHAR(250) NOT NULL UNIQUE 
	,ID_CLASSE INT FOREIGN KEY REFERENCES CLASSES(ID) NOT NULL
	,CAP_MAX_VIDA INT NOT NULL
	,CAP_MAX_MAN INT NOT NULL 
	,DATA_ATUALIZACAO DATETIME NOT NULL
	,DATA_CRIACAO DATETIME NOT NULL 
);

INSERT INTO CLASSES 
VALUES ('Bárbaro'),('Cruzado'),('Caçadora de Demônios'),('Monge'),('Necromante'),('Feiticeiro'),('Arcanista')

INSERT INTO TIPO_HABILIDADE
VALUES ('Ataque'),('Defesa'),('Cura'),('Magia')

INSERT INTO HABILIDADES
VALUES ('Lança Mortal',1),('Escudo Supremo',2),('Recuperar Vida',3)

INSERT INTO PERSONAGEM
VALUES ('DeuBug',1,100,80,'04/02/2019','18/01/2019'),('BigBug',4,70,100,'04/02/2019','17/03/2016'),('Fer8',7,75,60,'04/02/2019','18/03/2018')

UPDATE PERSONAGEM SET NOME = 'Fer7' WHERE ID = 3 

UPDATE CLASSES SET NOME = 'Necromancer' WHERE ID = 5 

SELECT *FROM PERSONAGEM  

SELECT *FROM CLASSES  

SELECT NOME FROM CLASSES  

SELECT *FROM HABILIDADES  

SELECT COUNT (*) FROM HABILIDADES

SELECT ID FROM HABILIDADES ORDER BY ID

SELECT *FROM TIPO_HABILIDADE

SELECT *FROM HABILIDADES, TIPO_HABILIDADE WHERE ID_TIPO_HABILIDADE = ID_TIPO_HABILIDADE

SELECT *FROM PERSONAGEM,CLASSES WHERE PERSONAGEM.ID_CLASSE = CLASSES.ID

SELECT PERSONAGEM.*,CLASSES.NOME FROM PERSONAGEM
RIGHT JOIN CLASSES ON PERSONAGEM.ID_CLASSE = CLASSES.ID

SELECT *FROM CLASSES_HABILIDADES

INSERT CLASSES_HABILIDADES 
VALUES (1,1), (1,2), (2,1), (3,1), (4,3), (4,2), (6,3)

SELECT * FROM CLASSES_HABILIDADES
INNER JOIN CLASSES ON CLASSES.ID = CLASSES_HABILIDADES.ID_CLASSE
INNER JOIN HABILIDADES ON HABILIDADES.ID = CLASSES_HABILIDADES.ID_HABILIDADE

SELECT * FROM CLASSES_HABILIDADES
INNER JOIN HABILIDADES ON HABILIDADES.ID = CLASSES_HABILIDADES.ID_HABILIDADE
INNER JOIN CLASSES ON CLASSES.ID = CLASSES_HABILIDADES.ID_CLASSE

SELECT * FROM CLASSES_HABILIDADES
RIGHT JOIN HABILIDADES ON HABILIDADES.ID = CLASSES_HABILIDADES.ID_HABILIDADE
RIGHT JOIN CLASSES ON CLASSES.ID = CLASSES_HABILIDADES.ID_CLASSE